# Path where your sets will be created (original sets will be left untouched)
exportDir = /mnt/local-ssd/ephemeral/best-arcade-rpi
# Path to your fbneo set, leave empty if you do not have it
fbneo = /mnt/barracuda/ephemeral/torrent/new/fbnarcade-fullnonmerged
# Path to your mame2010 set, leave empty if you do not have it
mame2010 = 
# Path to your mame2003 set, leave empty if you do not have it
mame2003 = /mnt/barracuda/ephemeral/torrent/new/MAME_2003-Plus_Reference_Set_2018/roms
# Path to your mame2003plus set, leave empty if you do not have it
mame2003plus = 
# Paths to your images set, leave empty if you do not have it
images = |
# Format of the image filename
imgNameFormat = 
# Check this to generate only dat and CSV files, no roms will be copied
dryRun = 0
# Select minimum working level at which roms will be kept
keepLevel = 3
# Check to keep untested roms even in STRICT mode
keepNotTested = 0
# Determine how roms are kept if they are in different sets
# STRICT (only keep the best working one), EQUAL (keep in several sets if equals in both), NONE (keep in all sets)
exclusionType = STRICT
# General prefered set in STRICT mode if rom is in same working level in several sets
preferedSet = fbneo
# Check to use prefered set for genres in STRICT mode and define them. Takes precedence over general prefered set if activated
usePreferedSetForGenre = 1
# Prefered set for BeatEmUp games
BeatEmUpPreferedSet = fbneo
# Prefered set for Gun games
GunPreferedSet = mame2003
# Prefered set for Misc games
MiscPreferedSet = fbneo
# Prefered set for Platform games
PlatformPreferedSet = fbneo
# Prefered set for Puzzle games
PuzzlePreferedSet = fbneo
# Prefered set for Race games
RacePreferedSet = fbneo
# Prefered set for RunNGun games
RunNGunPreferedSet = fbneo
# Prefered set for Shmup games
ShootEmUpPreferedSet = fbneo
# Prefered set for Sport games
SportPreferedSet = fbneo
# Prefered set for VsFighting games
VsFightingPreferedSet = fbneo
# Check to use genre subfolders for roms
genreSubFolders = 1
# Check to use images for games and folders
useImages = 0
